---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  releaseName: grafana
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: grafana
    version: 1.17.4
  values:
    datasources:
      prometheus:
        name: Prometheus
        type: prometheus
        access: proxy
        isDefault: true
        url: http://prometheus-server
...
