apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-password
  namespace: metrics
spec:
  encryptedData:
    values.yaml: AgAUg2bJ394gvViz6EshfTVqUtI3ngI+3DF4+e6SG/LyWZUcgDqfLX9VGmxoKTOgumNznJNFKw5lbeZPS4jFNBdNdZPzT+mIk396Km1lMTBCYZIWFRt3OzDJfROm9My40Lw+mrXOGzxqh3aReYggYQpgVsiqO03hBsuVxA7Ru/vh+EZrXxy0MfF0fvHJgaRdqKUyGMjoAw2DhfGo1IZu00sZYN2aEJW9KCcmQjqLv86Y+Fh0oVphw3VtfHbNB7jebw8GHtGEw2SFIG8In6dTGmQBmoNEZe/ohvBKtPoMwEX0Wmk9kSZzgXIIiCucXYMUhDovi333MV7v6hOwEkY+R1lEQeGULMG1TnOp5tnD8Z7JxoZ+XxZnCO4TSggYnmr8YvSj+gxLvbK8t4vCQsGKMB0Z8I3+uPBZ1n0hNMCWFvQrlo2i8mcRd001443tsyW82Z8+eRMUHE6DUXjSx0cpElsBw7WeFc68QECUaiXNDjEmBcsdtPWMH++Gc/X+IbtnLgcJbksMXT2FLSyOLu01Kdd+c8h4f2SE+HU1K5oeuRj1iLGAQCu058pjt6G+XsZT/nnEVHl4pulFyiJDnb7PIh5D8+iE0xn+VAwJGikFVEviHP37nXU8k1ov9Wmjah1gwhJ6BrLEq+QPRTvYtAvvrszgJE/hqLpecuOj1WKMH2dQEbjvAW+I0wJdi+ohfPMx0iZACxRJcAjiivBBm6PcY/8lfAwW8w0jDc/6P1KG5onA/QPdV6Hhei2cH6usM2dHe/x4

