---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
    version: 0.1.16
  values:
    kubeDns:
      enabled: true
    coreDns:
      enabled: false
    prometheusOperator:
      resources:
        requests:
          memory: 30Mi
    prometheus:
      prometheusSpec:
        resources:
          requests:
            memory: 275Mi
    alertmanager:
      alertmanagerSpec:
        resources:
          requests:
            memory: 25Mi
    grafana:
      resources:
        requests:
          memory: 100Mi
...
