---
helmOperator:
  create: true
  repository: quay.io/weaveworks/helm-operator
  tag: "0.5.2"
  resources:
    requests:
      memory: 100Mi
image:
  repository: quay.io/weaveworks/flux
  tag: "1.8.2"
git:
  url: ssh://git@github.com/mellena1/GKE-Deployments
  branch: master
  path: prod
resources:
  requests:
    memory: 100Mi
...
